---
- name: Check if SSL certs already exist
  stat:
    path: /etc/letsencrypt/live/{{ app_domain }}/privkey.pem
  register: ssl_certs_exist

- name: Create Certbot init script
  template:
    src: certbot-init.sh.j2
    dest: "{{ certbot_scripts_dir }}/certbot-init"
    owner: "{{ ssl_management_user }}"
    group: "{{ ssl_management_user }}"
    mode: 'u=rwx,g=rx,o=r'

- name: Run Certbot init script to fetch new certs
  command: "{{ certbot_scripts_dir }}/certbot-init"
  when: ssl_certs_exist.stat.exists == False
  notify:
    - Restart Nginx
